from pathlib import Path

ROOT = Path(__file__).parent
PRODUCTS = [
    (1, "เก้าอี้ไม้โค้ง", "6,900.00", "chair.jpg", "เก้าอี้ไม้ทรงโค้ง งานฝีมือประณีต ออกแบบมาเพื่อความสบายและความงามที่อยู่ได้นาน"),
    (2, "โต๊ะกาแฟทรงกลม", "8,500.00", "chair.jpg", "โต๊ะกาแฟดีไซน์ร่วมสมัย ขนาดพอดีสำหรับมุมโปรดของบ้าน"),
    (3, "ม้านั่งสั่งทำ", "12,000.00", "chair.jpg", "ม้านั่งดีไซน์เฉพาะตัว เลือกวัสดุ สี และขนาดให้เข้ากับพื้นที่ของคุณ"),
]
CSS = """
:root{--primary-color:#f4b400;--secondary-color:#263238;--text-muted:#68747a;--border-color:#e4e8ea;--surface:#fff;--background:#f5f7f8;--shadow-sm:0 2px 10px rgba(38,50,56,.08);--shadow-md:0 6px 22px rgba(38,50,56,.12)}
*{box-sizing:border-box}body{margin:0;color:var(--secondary-color);background:var(--background);font-family:"Leelawadee UI",Tahoma,sans-serif;line-height:1.6}a{color:inherit}header{padding:18px 20px;color:#fff;background:var(--secondary-color)}.header-inner{max-width:1100px;margin:auto}.brand{color:var(--primary-color);font-size:24px;font-weight:700}nav{margin-top:8px}nav a{margin-right:18px;color:#fff;text-decoration:none}nav a:hover{color:var(--primary-color)}.hero-banner{padding:68px 20px;color:#fff;text-align:center;background:linear-gradient(135deg,#263238,#455a64)}.hero-banner h1{margin:0 0 12px;font-size:clamp(30px,5vw,48px)}.hero-banner p{max-width:720px;margin:auto;color:#e6ecef}.section,.content{max-width:1100px;margin:40px auto 80px;padding:0 20px}.heading{text-align:center;margin-bottom:30px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:25px}.card{overflow:hidden;padding:20px;background:var(--surface);border:1px solid var(--border-color);border-radius:10px;box-shadow:var(--shadow-sm)}.card img{display:block;width:100%;height:220px;margin-bottom:15px;object-fit:cover;border-radius:8px}.card h2,.card h3{margin:0 0 8px}.muted{color:var(--text-muted);font-size:14px}.price{color:var(--primary-color);font-size:22px;font-weight:800}.btn,.btn-primary,.btn-yellow{display:inline-block;padding:10px 20px;color:#212121;background:var(--primary-color);border:0;border-radius:6px;font-weight:700;text-decoration:none;cursor:pointer}.btn-primary:hover,.btn-yellow:hover{background:#ffc928}.form-box{max-width:420px;margin:50px auto 80px;padding:40px;background:#fff;border-top:5px solid var(--primary-color);border-radius:15px;box-shadow:var(--shadow-md)}label{display:block;margin:0 0 7px;font-weight:600;font-size:14px}input,textarea,select{width:100%;padding:11px 14px;border:1px solid #ddd;border-radius:8px;font:inherit}.field{margin-bottom:18px}footer{padding:25px 20px;color:#dce3e6;text-align:center;background:var(--secondary-color)}.two-col{display:flex;flex-wrap:wrap;gap:30px}.two-col>*{flex:1;min-width:300px}
/* Furniture shop theme */
body{background:#f9f9f9;color:#333;font-family:"Kanit","Leelawadee UI",Tahoma,sans-serif}
header{display:flex;align-items:center;padding:15px 40px;gap:20px;flex-wrap:wrap;background:#fff;box-shadow:0 2px 5px rgba(0,0,0,.05)}
.header-inner{display:grid;grid-template-columns:auto minmax(180px,350px) minmax(0,1fr) auto auto;align-items:center;width:100%;gap:20px}.brand{color:#ff7a00;font-size:28px;font-weight:900;white-space:nowrap}.header-inner form{min-width:0;width:100%}.header-inner nav{display:flex;justify-content:center;gap:20px;align-items:center;min-width:0;overflow:hidden}.header-inner nav a{color:#333;text-decoration:none;font-weight:700;white-space:nowrap}.header-inner nav a[aria-current=page]{color:#ff7a00}.header-inner nav a:hover{color:#ff7a00}.auth-links{display:flex;gap:15px;align-items:center;white-space:nowrap}.auth-links[hidden],[data-user-menu][hidden]{display:none!important}.account{position:relative;min-width:max-content}.account-menu{position:absolute;right:0;top:calc(100% + 10px);z-index:30;min-width:190px;padding:8px;background:#fff;border:1px solid #eee;border-radius:8px;box-shadow:0 8px 24px rgba(0,0,0,.12)}.account-menu[hidden]{display:none!important}.account-menu.open{display:block}.account-menu a{display:block;padding:9px 12px;color:#333;text-decoration:none;font-size:14px;border-radius:5px}.account-menu a:hover{background:#f7f1e8;color:#b6893f}.account-menu .logout{color:#b3453a;border-top:1px solid #eee;margin-top:4px}
@media (max-width:1200px){header{padding:15px 24px}.header-inner{grid-template-columns:auto minmax(160px,1fr) auto auto;row-gap:12px}.header-inner nav{grid-column:1/-1;grid-row:2;justify-content:center;overflow-x:auto;padding:2px 0}.auth-links{margin-left:0}}
@media (max-width:700px){header{padding:14px 16px}.header-inner{grid-template-columns:1fr auto auto;gap:10px}.brand{font-size:23px}.header-inner form{grid-column:1/-1;grid-row:2}.header-inner nav{grid-column:1/-1;grid-row:3;justify-content:flex-start;overflow-x:auto}.header-inner nav a{font-size:13px}.auth-links{gap:8px;font-size:12px}.auth-links a:last-child{padding:6px 9px!important}.account-menu{right:-4px}}
 .hero-banner{padding:80px 20px;color:#fff;text-align:center;background:linear-gradient(135deg,#1a2530 0%,#2c3e50 100%)}.hero-banner h1{font-size:42px}.hero-banner p{color:#fff}.section,.content{background:transparent}.card{background:#fff;border-radius:10px;box-shadow:0 2px 8px rgba(0,0,0,.08)}.btn,.btn-primary,.btn-yellow{background:#ff7a00;color:#fff;border-radius:6px}.btn-primary:hover,.btn-yellow:hover{background:#e66d00}footer{color:#fff;background:#1a2530}
 @media (max-width:600px){header .header-inner form{width:100%;max-width:none!important;margin:0!important}.header-inner{min-width:0}header{overflow:hidden}}
"""

def image(filename, alt, size="300x220"):
    return f'<img src="images/{filename}" alt="{alt}" onerror="this.onerror=null;this.src=\'https://via.placeholder.com/{size}?text=Furniture\';">'

def cards():
    return ''.join(f'<article class="card">{image(pic,name)}<h3>{name}</h3><div class="price">฿{price}</div><p class="muted">{desc}</p><a class="btn-primary" data-login-required href="product_detail.html?id={pid}">ดูรายละเอียด</a></article>' for pid,name,price,pic,desc in PRODUCTS)

def page(title, body, active="index.php", script="", protected=False):
    links = [("index.php","หน้าหลัก"),("products.html","สินค้า"),("services.html","บริการ"),("promo.html","โปรโมชั่น"),("devices.html","อุปกรณ์"),("article.html","บทความ"),("furniture-designer.html","ออกแบบ 3D")]
    protected_pages = {"products.html", "product_detail.html", "cart.html", "checkout.html", "furniture-designer.html", "profile.html"}
    nav = ''.join(f'<a href="{href}"{" aria-current=page" if href == active else ""}{" data-login-required" if href in protected_pages else ""}>{label}</a>' for href,label in links)
    protection = ' data-protected-page="true"' if protected else ''
    account = '<div class="account" data-account><div class="auth-links" data-login-links><a href="login.html" style="color:#b6893f;font-weight:bold;text-decoration:none">เข้าสู่ระบบ</a><span style="color:#ddd">|</span><a href="register.html" style="background:#343632;color:#fff;padding:7px 12px;border-radius:5px;text-decoration:none">สมัครสมาชิก</a></div><div data-user-menu hidden><button data-user-toggle style="border:0;background:transparent;color:#b6893f;font-weight:bold;cursor:pointer"><span data-user-name>บัญชีของฉัน</span> ▾</button><div class="account-menu"><a href="profile.html">บัญชีของฉัน</a><a href="api_logout.php" data-logout class="logout">ออกจากระบบ</a></div></div></div>'
    return f'<!DOCTYPE html><html lang="th"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} - Maison Forme</title><style>{CSS}</style></head><body{protection}><header><div class="header-inner"><div class="brand"><a href="index.php" style="color:#b6893f;text-decoration:none">Maison Forme</a></div><form action="search.html" method="GET" style="display:flex;width:100%;max-width:350px;border:1px solid #ccc;border-radius:25px;overflow:hidden;margin:0 20px"><input type="text" name="keyword" placeholder="ค้นหาเฟอร์นิเจอร์..." style="flex:1;border:0;padding:10px 15px;outline:0"><button type="submit" style="background:#b6893f;color:#fff;border:0;padding:0 25px;cursor:pointer;font-weight:bold">ค้นหา</button></form><nav aria-label="เมนูหลัก">{nav}</nav><a href="cart.html" data-login-required aria-label="ตะกร้าสินค้า" style="font-size:24px;text-decoration:none">🛒</a>{account}</div></header><main>{body}</main><footer>© 2026 Maison Forme | ร้านเฟอร์นิเจอร์และของแต่งบ้าน</footer><script src="site.js"></script><script src="guard.js"></script><script src="account.js?v=4"></script>{script}</body></html>'

def form_page(title, register=False):
    extra = '<div class="field"><label>ยืนยันรหัสผ่าน</label><input name="confirm_password" type="password" required placeholder="กรอกรหัสผ่านอีกครั้ง"></div>' if register else ''
    link = 'login.html' if register else 'register.html'
    text = 'มีบัญชีอยู่แล้วใช่ไหม? เข้าสู่ระบบที่นี่' if register else 'ยังไม่มีบัญชีใช่ไหม? สมัครสมาชิกเลย'
    mode = 'register' if register else 'login'
    body = f'<section class="form-box"><h2>{title}</h2><form data-auth-form="{mode}"><div class="field"><label>ชื่อผู้ใช้</label><input name="username" required placeholder="กรอกชื่อผู้ใช้ของคุณ"></div><div class="field"><label>รหัสผ่าน</label><input name="password" type="password" minlength="6" required placeholder="กรอกรหัสผ่าน"></div>{extra}<p class="muted" data-auth-status></p><button class="btn-primary" type="submit">{title}</button></form><p class="muted"><a href="{link}">{text}</a></p></section>'
    return page(title, body, 'register.html' if register else 'login.html', '<script src="auth.js"></script>')

def build():
    home = f'<section class="hero-banner"><h1>เฟอร์นิเจอร์ที่ออกแบบเพื่อบ้านของคุณ</h1><p>เลือกชิ้นงานคุณภาพ หรือสร้างเฟอร์นิเจอร์ดีไซน์เฉพาะตัวด้วย AI</p><p><a class="btn-yellow" href="products.html">🛒 ชมคอลเลกชัน</a></p></section><section class="section"><div class="heading"><h2>สิทธิพิเศษประจำเดือน</h2><p>โปรโมชั่นพิเศษสำหรับคนรักบ้านและงานดีไซน์</p></div><div class="grid"><a class="card" href="promo.html">{image("chair.jpg","ส่วนลดเฟอร์นิเจอร์","500x300")}<h3>ส่วนลดชิ้นงานสั่งทำ</h3><p class="muted">รับส่วนลดพิเศษเมื่อสั่งซื้อเฟอร์นิเจอร์ครบตามยอดที่กำหนด</p></a><a class="card" href="promo.html">{image("chair.jpg","จัดส่งและติดตั้ง","500x300")}<h3>จัดส่งและติดตั้งอย่างใส่ใจ</h3><p class="muted">ดูแลทุกขั้นตอนตั้งแต่เลือกแบบจนถึงวันที่ชิ้นงานเข้าบ้าน</p></a></div><p style="text-align:center"><a class="btn-yellow" href="promo.html">ดูโปรโมชั่นทั้งหมด</a></p></section><section class="section"><div class="heading"><h2>ชิ้นงานแนะนำ</h2></div><div class="grid"><article class="card">{image("chair.jpg","เก้าอี้ไม้โค้ง")}<h4>เก้าอี้ไม้โค้ง</h4><p class="price">เริ่มต้น 6,900.-</p></article><article class="card">{image("chair.jpg","โต๊ะกาแฟทรงกลม")}<h4>โต๊ะกาแฟทรงกลม</h4><p class="price">เริ่มต้น 8,500.-</p></article><article class="card">{image("chair.jpg","ม้านั่งสั่งทำ")}<h4>ม้านั่งสั่งทำ</h4><p class="price">เริ่มต้น 12,000.-</p></article></div></section>'
    pages = {
        'products.html': page('คอลเลกชันเฟอร์นิเจอร์', '<section class="hero-banner"><h1>คอลเลกชันเฟอร์นิเจอร์</h1><p>เลือกชมเฟอร์นิเจอร์คุณภาพและของแต่งบ้านที่คัดสรรมาเพื่อคุณ</p></section><section class="content"><div class="grid product-grid" data-products-api="api_products.php">'+cards()+'</div></section>', 'products.html', protected=True),
        'promo.html': page('โปรโมชั่น', '<section class="hero-banner"><h1>โปรโมชั่นสุดพิเศษ</h1><p>สิทธิพิเศษสำหรับเฟอร์นิเจอร์และชิ้นงานสั่งทำประจำเดือนนี้</p></section><section class="content" data-content-page="promo"><div class="grid" data-content-list></div></section>', 'promo.html', '<script src="content.js"></script>'),
        'services.html': page('บริการของเรา', '<section class="hero-banner"><h1>บริการของเรา</h1><p>ตั้งแต่ไอเดียแรกจนถึงเฟอร์นิเจอร์ชิ้นพิเศษในบ้านคุณ</p></section><section class="content" data-content-page="services"><div class="grid" data-content-list></div></section>', 'services.html', '<script src="content.js"></script>'),
        'devices.html': page('เครื่องมือออกแบบ', '<section class="hero-banner"><h1>เครื่องมือออกแบบ</h1><p>สร้างและปรับแต่งเฟอร์นิเจอร์ของคุณในสตูดิโอ 3 มิติ</p></section><section class="content" data-content-page="devices"><div class="grid" data-content-list></div><p style="text-align:center"><a class="btn-primary" data-login-required href="furniture-designer.html">เข้าสู่สตูดิโอ 3D</a></p></section>', 'devices.html', '<script src="content.js"></script>'),
        'article.html': page('ไอเดียแต่งบ้าน', '<section class="hero-banner"><h1>ไอเดียแต่งบ้าน</h1><p>แรงบันดาลใจในการเลือกเฟอร์นิเจอร์และสร้างพื้นที่ที่เป็นตัวคุณ</p></section><section class="content"><div class="grid"><article class="card">'+image('article1.jpg','คู่มือเลือกเฟอร์นิเจอร์ไม้','400x250')+'<h2>เลือกเฟอร์นิเจอร์ไม้ให้เข้ากับบ้าน</h2><p class="muted">ทำความรู้จักวัสดุ โทนสี และรูปทรงที่ช่วยสร้างบรรยากาศอบอุ่น</p></article><article class="card">'+image('article2.jpg','การจัดห้องอย่างมีสไตล์','400x250')+'<h2>จัดห้องให้สวยและใช้งานได้จริง</h2><p class="muted">เคล็ดลับการเลือกขนาดและจัดวางเฟอร์นิเจอร์ให้เหมาะกับพื้นที่</p></article></div></section>', 'article.html'),
        'login.html': form_page('เข้าสู่ระบบ'),
        'register.html': form_page('สมัครสมาชิก', True),
        'profile.html': page('แก้ไขข้อมูลส่วนตัว', '<section class="form-box"><h2>แก้ไขข้อมูลส่วนตัว</h2><form data-profile-form><div class="field"><label>ชื่อผู้ใช้</label><input name="username" required minlength="3"></div><div class="field"><label>รหัสผ่านใหม่ (เว้นว่างหากไม่เปลี่ยน)</label><input name="password" type="password" minlength="6" placeholder="กรอกรหัสผ่านใหม่"></div><p class="muted" data-profile-status></p><button class="btn-primary" type="submit">บันทึกข้อมูล</button></form></section>', 'profile.html', '<script src="profile.js"></script>', protected=True),
        'cart.html': page('ตะกร้าสินค้า', '<section class="content"><h1>🛒 ตะกร้าสินค้าของฉัน</h1><div class="card" style="text-align:center;padding:80px 20px"><h3>ไม่มีสินค้าในตะกร้า</h3><a class="btn-primary" href="products.html">เลือกซื้อสินค้าเลย</a></div></section>', 'cart.html', protected=True),
        'history.html': page('ประวัติการสั่งซื้อ', '<section class="content"><div class="card" style="text-align:center;padding:70px 20px"><h2>📜 ประวัติการสั่งซื้อของคุณ</h2><h3>คุณยังไม่มีประวัติการสั่งซื้อ</h3><a class="btn-primary" href="products.html">กลับไปเลือกซื้อสินค้า</a></div></section>', 'history.html'),
        'search.html': page('ผลการค้นหา', '<section class="hero-banner"><h1>ผลการค้นหา</h1><p id="searchSummary">ค้นหาสินค้าจากรายการด้านล่าง</p></section><section class="content"><form method="GET" action="search.html"><div class="field"><input name="keyword" value="" placeholder="ค้นหาเฟอร์นิเจอร์ เช่น เก้าอี้ โต๊ะ โซฟา" required></div><button class="btn-primary" type="submit">ค้นหา</button></form><div class="grid product-grid" data-search-results></div></section>', 'search.html'),
        'product_detail.html': page('รายละเอียดสินค้า', '<section class="content two-col product-detail" data-product-detail><div class="card"><img id="productImage" src="images/chair.jpg" alt="สินค้า"></div><div class="card"><h1 id="productName">กำลังโหลดสินค้า...</h1><div class="price" id="productPrice"></div><p class="muted" id="productDescription"></p><form id="addToCartForm"><div class="field"><label>วัสดุ / สี</label><select><option>ไม้โอ๊คธรรมชาติ</option><option>ไม้เข้มวอลนัท</option><option>สีตามสั่ง</option></select></div><div class="field"><label>จำนวนที่ต้องการ</label><input id="productQty" type="number" value="1" min="1"></div><button class="btn-primary" type="submit">🛒 เพิ่มสินค้าลงตะกร้า</button></form></div></section>', 'product_detail.html', '<script src="product_detail.js"></script>', protected=True),
        'checkout.html': page('ยืนยันการสั่งซื้อ', '<section class="content two-col"><div class="card"><h2>📍 ข้อมูลการจัดส่ง</h2><form onsubmit="alert(\'ระบบ HTML นี้ไม่บันทึกคำสั่งซื้อ\');return false"><div class="field"><label>ชื่อ-นามสกุล (ผู้รับ)</label><input required></div><div class="field"><label>เบอร์โทรศัพท์</label><input required></div><div class="field"><label>ที่อยู่จัดส่งแบบละเอียด</label><textarea rows="4" required></textarea></div><div class="field"><label>วิธีการชำระเงิน</label><select required><option value="">-- กรุณาเลือกวิธีชำระเงิน --</option><option>สแกน QR Code (PromptPay)</option><option>เก็บเงินปลายทาง (COD)</option></select></div><button class="btn-primary">✅ ยืนยันคำสั่งซื้อและชำระเงิน</button></form></div><div class="card"><h2>🛒 สรุปคำสั่งซื้อ</h2><p>ยังไม่มีสินค้าในตะกร้า</p></div></section>', 'checkout.html', protected=True),
    }
    for filename, content in pages.items():
        (ROOT / filename).write_text(content, encoding='utf-8')
if __name__ == '__main__':
    build()
